version: '2.1'

services:
  app:
    platform: linux/x86_64
    restart: always
    build: ./
    volumes:
      - ioi_static:/usr/src/app/static/
      - /media:/usr/src/app/media/
    depends_on:
      - redis
    env_file:
      # See .env.app.example for the template.
      - .env.app.prod

  nginx:
    image: jonasal/nginx-certbot:latest
    restart: always
    env_file:
      - .env.nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app
    volumes:
      - ioi_static:/usr/src/app/static/:ro
      - /media:/usr/src/app/media/:ro
      - ./nginx/templates.boi:/etc/nginx/templates:ro
      - ./nginx/translation.htpasswd:/etc/nginx/passwords/translation.htpasswd:ro
      - nginx_secrets:/etc/letsencrypt

  redis:
    restart: always
    image: redis:3.2-alpine

volumes:
  ioi_static:
  nginx_secrets:
