version: '2.1'

services:
  app:
    platform: linux/x86_64
    restart: always
    build: ./
    volumes:
      - ioi_static:/usr/src/app/static/
      - /media:/usr/src/app/media/
    depends_on:
      - redis
    env_file:
      # See .env.app.example for the template.
      - .env.app.prod

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - 9000:80
    depends_on:
      - app
    volumes:
      - ioi_static:/usr/src/app/static/:ro
      - /media:/usr/src/app/media/:ro

  redis:
    restart: always
    image: redis:3.2-alpine

volumes:
  ioi_static:
