version: '2.1'

services:
  app:
    platform: linux/x86_64
    restart: always
    build: ./
    ports:
      - 9001:8000 # Debugging
    volumes:
      - .:/usr/src/app/ # Debugging
      - ioi_static:/usr/src/app/static/
      - ioi_media:/usr/src/app/media/
    depends_on:
      - postgres
      - redis
    env_file:
      - .env.app.dev

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - 9000:80
    depends_on:
      - app
    volumes:
      - ioi_static:/usr/src/app/static/:ro
      - ioi_media:/usr/src/app/media/:ro

  postgres:
    restart: always
    image: postgres:9.6-alpine
    volumes:
      - ioi_pgdata:/var/lib/postgresql/data/
    env_file:
      - .env.app.dev
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

  redis:
    restart: always
    image: redis:3.2-alpine

volumes:
  ioi_pgdata:
  ioi_static:
  ioi_media:
